[build]
  # 构建命令
  command = "cd frontend && npm install && npm run build"
  # 发布目录
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "18"

# 单页应用路由配置
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API 代理配置（如果需要）
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-api.com/api/:splat"
  status = 200
  force = true

# 安全头配置
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# 缓存配置
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
